In [1]:
# Intern Performance Analytics
## Sprint 1: Data Preparation

# importing required libraries
import pandas as pd
import numpy as np

In [2]:
# loading the dataset
df = pd.read_csv(r"C:\Users\91948\Downloads\intern_performance_raw datasets.csv")

# just checking first few rows
df.head()

,intern_id,name,age,gender,department,internship_duration,attendance_rate,task_completion_rate,punctuality_score,communication_score,teamwork_score,technical_score,problem_solving_score,initiative_score,project_score,mentor_feedback_score,training_hours,certifications,late_submissions,extra_activities
0,1,Intern_1,27,male,Data Science,9,91,88,5.6,9.5,7.5,NaN,5.1,9.3,94,9.9,79,3,5,No
1,2,Intern_2,22,Female,Marketing,Six,94,54,5.6,NaN,8.0,6.7,5.8,5.2,44,6.7,65,4,5,yes
2,3,Intern_3,27,female,Data Science,9,83,70,3.8,8.4,9.4,4.9,7.7,3.9,54,NaN,144,1,0,No
3,4,Intern_4,27,Female,Web Dev,Six,85,86,4.2,NaN,7.0,5.1,4.5,7.2,69,NaN,61,2,13,No
4,5,Intern_5,19,male,IoT,Six,63,77,4.2,4.0,7.3,4.4,10.0,5.3,92,8.0,142,3,3,no

In [3]:
# checking basic info about the data
df.shape
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   intern_id              1050 non-null   int64
 1   name                   1050 non-null   object
 2   age                    1050 non-null   int64
 3   gender                 1050 non-null   object
 4   department             1050 non-null   object
 5   internship_duration    1050 non-null   object
 6   attendance_rate        1050 non-null   int64
 7   task_completion_rate   1050 non-null   int64
 8   punctuality_score      1050 non-null   float64
 9   communication_score    887 non-null    float64
 10  teamwork_score         1050 non-null   float64
 11  technical_score        894 non-null    float64
 12  problem_solving_score  1050 non-null   float64
 13  initiative_score       1050 non-null   float64
 14  project_score          1050 non-null   int64
 15  mentor_feedback_score  896 non-null    float64
 16  training_hours         1050 non-null   int64
 17  certifications         1050 non-null   int64
 18  late_submissions       1050 non-null   int64
 19  extra_activities       1050 non-null   object
dtypes: float64(7), int64(8), object(5)
memory usage: 164.2+ KB

In [6]:
# looking at summary statistics
df.describe()

,intern_id,age,attendance_rate,task_completion_rate,punctuality_score,communication_score,teamwork_score,technical_score,problem_solving_score,initiative_score,project_score,mentor_feedback_score,training_hours,certifications,late_submissions
count,1050.000000,1050.000000,1050.000000,1050.000000,1050.000000,887.000000,1050.000000,894.000000,1050.000000,1050.000000,1050.000000,896.000000,1050.000000,1050.000000,1050.000000
mean,496.626667,22.922857,80.151429,74.496190,6.467810,6.602255,6.613619,6.544072,6.513810,6.411619,70.743810,6.563951,77.673333,2.944762,6.857143
std,290.263352,2.588151,11.531650,15.010403,2.012362,1.976908,2.051658,2.027080,2.040881,2.024619,17.585257,1.967480,42.471759,2.005425,4.242031
min,1.000000,19.000000,60.000000,50.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,40.000000,3.000000,5.000000,0.000000,0.000000
25%,243.250000,21.000000,70.000000,61.000000,4.800000,5.000000,4.800000,4.800000,4.800000,4.700000,55.250000,4.900000,41.000000,1.000000,3.000000
50%,496.500000,23.000000,80.000000,74.000000,6.450000,6.500000,6.700000,6.500000,6.500000,6.400000,72.000000,6.500000,79.000000,3.000000,7.000000
75%,747.750000,25.000000,90.000000,87.000000,8.200000,8.400000,8.500000,8.375000,8.300000,8.200000,86.000000,8.200000,114.000000,5.000000,10.000000
max,1000.000000,27.000000,100.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,100.000000,10.000000,149.000000,6.000000,14.000000

In [7]:
# checking for missing values
df.isnull().sum()

intern_id                  0
name                       0
age                        0
gender                     0
department                 0
internship_duration        0
attendance_rate            0
task_completion_rate       0
punctuality_score          0
communication_score      163
teamwork_score             0
technical_score          156
problem_solving_score      0
initiative_score           0
project_score              0
mentor_feedback_score    154
training_hours             0
certifications             0
late_submissions           0
extra_activities           0
dtype: int64

In [23]:
# filling missing values using median 
for col in ['communication_score', 'technical_score', 'mentor_feedback_score']:
    df[col] = df[col].fillna(df[col].median())

In [9]:
# rechecking missing values
df.isnull().sum()

intern_id                0
name                     0
age                      0
gender                   0
department               0
internship_duration      0
attendance_rate          0
task_completion_rate     0
punctuality_score        0
communication_score      0
teamwork_score           0
technical_score          0
problem_solving_score    0
initiative_score         0
project_score            0
mentor_feedback_score    0
training_hours           0
certifications           0
late_submissions         0
extra_activities         0
dtype: int64

In [10]:
# cleaning text columns
df['gender'] = df['gender'].str.lower().str.strip()
df['department'] = df['department'].str.lower().str.strip()
df['extra_activities'] = df['extra_activities'].str.lower().str.strip()

In [11]:
# converting yes/no into numbers
df['extra_activities'] = df['extra_activities'].map({'yes': 1, 'no': 0})

In [21]:
# fixing internship duration (handling text + numbers)

df['internship_duration'] = df['internship_duration'].astype(str).str.lower().str.strip()

word_to_num = {
    'one': 1, 'two': 2, 'three': 3, 'four': 4,
    'five': 5, 'six': 6, 'seven': 7, 'eight': 8,
    'nine': 9, 'ten': 10
}

df['internship_duration'] = df['internship_duration'].replace(word_to_num)

df['internship_duration'] = df['internship_duration'].astype(str).str.extract(r'(\d+)')[0]

df['internship_duration'] = pd.to_numeric(df['internship_duration'], errors='coerce')

df['internship_duration'] = df['internship_duration'].fillna(df['internship_duration'].median())

df['internship_duration'] = df['internship_duration'].astype(int)

In [22]:
# verifying internship_duration
df['internship_duration'].unique()
df['internship_duration'].isnull().sum()
df['internship_duration'].head()

0    9
1    6
2    9
3    6
4    6
Name: internship_duration, dtype: int32

In [12]:
# checking duplicates
df.duplicated().sum()

50

In [13]:
# removing duplicates
df.drop_duplicates(inplace=True)

In [14]:
# creating new columns

df['overall_performance'] = (
    df['task_completion_rate'] +
    df['project_score'] +
    df['technical_score']
) / 3

df['soft_skills_score'] = (
    df['communication_score'] +
    df['teamwork_score'] +
    df['initiative_score']
) / 3

df['discipline_score'] = df['attendance_rate'] - df['late_submissions']

In [15]:
# final validation
df.isnull().sum()
df.describe()

,intern_id,age,attendance_rate,task_completion_rate,punctuality_score,communication_score,teamwork_score,technical_score,problem_solving_score,initiative_score,project_score,mentor_feedback_score,training_hours,certifications,late_submissions,extra_activities,overall_performance,soft_skills_score,discipline_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,22.930000,80.177000,74.455000,6.46600,6.591400,6.613100,6.552200,6.5377,6.421500,70.8020,6.544200,77.551000,2.948000,6.924000,0.49000,50.603067,6.542000,73.253000
std,288.819436,2.586463,11.591291,14.937976,2.01777,1.828521,2.053766,1.875338,2.0374,2.028345,17.6003,1.827448,42.489042,1.993808,4.255389,0.50015,7.706150,1.138264,12.202208
min,1.000000,19.000000,60.000000,50.000000,3.00000,3.000000,3.000000,3.000000,3.0000,3.000000,40.0000,3.000000,5.000000,0.000000,0.000000,0.00000,32.900000,3.533333,46.000000
25%,250.750000,21.000000,70.000000,61.000000,4.80000,5.300000,4.800000,5.200000,4.8000,4.700000,55.0000,5.200000,40.750000,1.000000,3.000000,0.00000,45.200000,5.733333,64.000000
50%,500.500000,23.000000,80.000000,74.000000,6.50000,6.500000,6.700000,6.500000,6.5000,6.500000,72.0000,6.500000,78.500000,3.000000,7.000000,0.00000,50.583333,6.566667,73.000000
75%,750.250000,25.000000,90.000000,87.000000,8.20000,8.000000,8.500000,7.925000,8.3000,8.200000,86.0000,7.900000,114.000000,5.000000,11.000000,1.00000,56.175000,7.333333,83.000000
max,1000.000000,27.000000,100.000000,100.000000,10.00000,10.000000,10.000000,10.000000,10.0000,10.000000,100.0000,10.000000,149.000000,6.000000,14.000000,1.00000,69.033333,9.366667,100.000000

In [25]:
# saving updated cleaned dataset
df.to_csv(r"C:\Users\91948\Downloads\cleaned_intern_dataset.csv", index=False)

In [27]:
# checking basic data
df.head()
df.shape

# checking missing values
df.isnull().sum()

# checking internship duration cleaned properly
df['internship_duration'].unique()

# checking duplicates
df.duplicated().sum()

# checking new columns
df[['overall_performance', 'soft_skills_score', 'discipline_score']].head()

# checking data summary
df.describe()

,intern_id,age,internship_duration,attendance_rate,task_completion_rate,punctuality_score,communication_score,teamwork_score,technical_score,problem_solving_score,initiative_score,project_score,mentor_feedback_score,training_hours,certifications,late_submissions,extra_activities,overall_performance,soft_skills_score,discipline_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,22.930000,6.057000,80.177000,74.455000,6.46600,6.591400,6.613100,6.552200,6.5377,6.421500,70.8020,6.544200,77.551000,2.948000,6.924000,0.49000,50.603067,6.542000,73.253000
std,288.819436,2.586463,2.106701,11.591291,14.937976,2.01777,1.828521,2.053766,1.875338,2.0374,2.028345,17.6003,1.827448,42.489042,1.993808,4.255389,0.50015,7.706150,1.138264,12.202208
min,1.000000,19.000000,3.000000,60.000000,50.000000,3.00000,3.000000,3.000000,3.000000,3.0000,3.000000,40.0000,3.000000,5.000000,0.000000,0.000000,0.00000,32.900000,3.533333,46.000000
25%,250.750000,21.000000,6.000000,70.000000,61.000000,4.80000,5.300000,4.800000,5.200000,4.8000,4.700000,55.0000,5.200000,40.750000,1.000000,3.000000,0.00000,45.200000,5.733333,64.000000
50%,500.500000,23.000000,6.000000,80.000000,74.000000,6.50000,6.500000,6.700000,6.500000,6.5000,6.500000,72.0000,6.500000,78.500000,3.000000,7.000000,0.00000,50.583333,6.566667,73.000000
75%,750.250000,25.000000,9.000000,90.000000,87.000000,8.20000,8.000000,8.500000,7.925000,8.3000,8.200000,86.0000,7.900000,114.000000,5.000000,11.000000,1.00000,56.175000,7.333333,83.000000
max,1000.000000,27.000000,9.000000,100.000000,100.000000,10.00000,10.000000,10.000000,10.000000,10.0000,10.000000,100.0000,10.000000,149.000000,6.000000,14.000000,1.00000,69.033333,9.366667,100.000000

In [28]:
# loading again to verify saved file
df_clean = pd.read_csv(r"C:\Users\91948\Downloads\cleaned_intern_dataset.csv")

# checking saved data
df_clean.head()
df_clean.isnull().sum()
df_clean['internship_duration'].unique()

array([9, 6, 3], dtype=int64)